name: uit-buddy-ai

services:
  services:
  n8n:
    name: n8n
    image: docker.n8n.io/n8nio/n8n
    restart: always
    ports:
      - ${HOST_N8N_PORT}:5678
    volumes:
      - n8n_data:/data
  
volumes:
  n8n_data: